name: Test Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # allows manual triggering

jobs:
  test-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          logger: pretty

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Test base package
        run: |
          echo "Testing nvim (base package)..."
          nix build .#nvim --no-link
          nix run .#nvim -- --version

      - name: Test Rust package
        run: |
          echo "Testing nvim-rust package..."
          nix build .#nvim-rust --no-link
          nix run .#nvim-rust -- --version

      - name: Test Web package
        run: |
          echo "Testing nvim-web package..."
          nix build .#nvim-web --no-link
          nix run .#nvim-web -- --version

      - name: Test Nix package
        run: |
          echo "Testing nvim-nix package..."
          nix build .#nvim-nix --no-link
          nix run .#nvim-nix -- --version

      - name: Test Python package
        run: |
          echo "Testing nvim-python package..."
          nix build .#nvim-python --no-link
          nix run .#nvim-python -- --version

      - name: Test Go package
        run: |
          echo "Testing nvim-go package..."
          nix build .#nvim-go --no-link
          nix run .#nvim-go -- --version

      - name: Test Writing package
        run: |
          echo "Testing nvim-writing package..."
          nix build .#nvim-writing --no-link
          nix run .#nvim-writing -- --version

      - name: Test Full package
        run: |
          echo "Testing nvim-full package..."
          nix build .#nvim-full --no-link
          nix run .#nvim-full -- --version

      - name: Test plugin conditionals
        run: |
          echo "Testing conditional plugin loading..."
          
          # Create test script
          cat > test-plugin-loading.lua << 'EOF'
          local nixCatsUtils = require('nixCatsUtils')
          
          local function test_plugin_enablement()
            local obsidian_enabled = nixCatsUtils.enableForCategory("custom-obsidian")
            local vimtex_enabled = nixCatsUtils.enableForCategory("custom-vimtex")
            local writing_enabled = nixCatsUtils.enableForCategory("writing")
            
            print(string.format("obsidian:%s vimtex:%s writing:%s", 
              obsidian_enabled and "1" or "0",
              vimtex_enabled and "1" or "0", 
              writing_enabled and "1" or "0"))
          end
          
          test_plugin_enablement()
          EOF
          
          # Test writing package (should enable obsidian/vimtex)
          echo "Testing nvim-writing plugin loading..."
          WRITING_RESULT=$(nix run .#nvim-writing -- --headless -u NONE -i NONE -E -s -l test-plugin-loading.lua)
          echo "Writing package result: $WRITING_RESULT"
          if [[ "$WRITING_RESULT" != *"obsidian:1 vimtex:1 writing:1"* ]]; then
            echo "❌ Writing package should enable obsidian and vimtex"
            exit 1
          fi
          
          # Test development package (should disable obsidian/vimtex)  
          echo "Testing nvim-nix plugin loading..."
          NIX_RESULT=$(nix run .#nvim-nix -- --headless -u NONE -i NONE -E -s -l test-plugin-loading.lua)
          echo "Nix package result: $NIX_RESULT"
          if [[ "$NIX_RESULT" != *"obsidian:0 vimtex:0 writing:0"* ]]; then
            echo "❌ Nix development package should disable obsidian and vimtex"
            exit 1
          fi
          
          # Test full package (should enable everything)
          echo "Testing nvim-full plugin loading..."
          FULL_RESULT=$(nix run .#nvim-full -- --headless -u NONE -i NONE -E -s -l test-plugin-loading.lua)
          echo "Full package result: $FULL_RESULT"
          if [[ "$FULL_RESULT" != *"obsidian:1 vimtex:1 writing:1"* ]]; then
            echo "❌ Full package should enable all plugins"
            exit 1
          fi
          
          echo "✅ Plugin conditional loading works correctly!"
          rm test-plugin-loading.lua

      - name: Test devShells
        run: |
          echo "Testing development shells..."
          nix develop .#nvim-rust --command echo "Rust devShell works"
          nix develop .#nvim-web --command echo "Web devShell works"
          nix develop .#nvim-python --command echo "Python devShell works"
          nix develop .#nvim-go --command echo "Go devShell works"

      - name: Check flake
        run: |
          echo "Running flake check..."
          nix flake check

      - name: Summary
        run: |
          echo "✅ All packages build and run successfully!"
          echo "✅ Plugin conditional loading works correctly!"
          echo "✅ All development shells work!"
          echo "✅ Flake check passed!"
